apiVersion: v1
kind: Pod
metadata:
  labels:
    azure.workload.identity/use: "true"
  name: nginx
spec:
  serviceAccountName: cluster-workload-user
  containers:
  - image: nginx
    name: nginx
    resources: {}
  restartPolicy: Always